data_ingestion:
  source_path: data/external/tweets_v8.csv
  test_size: 0.20

data_labeling:
  positive_threshold: 0.05
  negative_threshold: -0.05

model_building:
  ngram_range: [1, 3]
  max_features: 10000
  learning_rate: 0.09
  max_depth: 20
  n_estimators: 367
